# version: '2'
services:
  web:
    build: .
    # image: poonlap/odoo-th:16.0
    command: -- --dev=all --init base_setup
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web:/var/lib/odoo 
      # ./data:/var/lib/odoo # You need to change the permission of data folder to be writable by docker deamone.
  db:
    image: postgres:12 # Odoo 16.0 needs Postgres 12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-db-data:
  odoo-web:
